server:
  port: 8080
spring:
  cloud:
    nacos:
      username: nacos
      password: nacos
      config:
        server-addr: 127.0.0.1:8848
      discovery:
        server-addr: 127.0.0.1:8848
  config:
    import: nacos:test?refresh=true&group=DEFAULT_GROUP
