server:
  port: 8080
spring:
  cloud:
    nacos:
      username: nacos
      password: nacos
      config:
        server-addr: 127.0.0.1:8848
      discovery:
        server-addr: 127.0.0.1:8848
  config:
    import: nacos:test?refresh=true&group=DEFAULT_GROUP
  datasource:
    url: jdbc:mysql://localhost:3306/ms?useSSL=false&serverTimezone=UTC
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapper/*.xml
#  type-aliases-package: com.example.mybatisdemo.entity

test:
  val2: test2